# Generated by Django 3.1 on 2020-08-26 14:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
